<a href="https://colab.research.google.com/github/SahanaMukunda/DS_BRAD/blob/main/Python_basics_BRAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

operation(+,-,*,%,<=,>=,<,>,not, &, | )

In [43]:
3 > 10

False

In [4]:
1+2

3

In [6]:
10-2

8

In [8]:
20*45

900

In [11]:
256/22560

0.011347517730496455

In [13]:
10==10

True

In [15]:
12!=13

True

In [18]:
12>13

False

In [19]:
15<16

True

In [21]:
456<=345

False

In [22]:
3435>=234

True

In [23]:
1000>445

True

In [24]:
232<3443

True

In [26]:
458&7889

192

In [27]:
323232|434343

454311

In [32]:
not(10==10)

False

In [33]:
(10>20)&(20>10)

False

In [34]:
(10>20)|(20>10)

True

Looping statments:

While loop:

In [38]:
i=0
while i<=5:
  print(i)
  i=i+1

0
1
2
3
4
5


In [40]:
i=0
while i<=5:
  print(i)
  i=i+1
  #shift+tab=new line or out of current loop
print("loop ends")

0
1
2
3
4
5
loop ends


range and list



range(6)

In [41]:
list(range(6))

[0, 1, 2, 3, 4, 5]

for loop

In [42]:
for i in range(6):
  print("hello world")

hello world
hello world
hello world
hello world
hello world
hello world


IF statment


In [44]:
import numpy as np
from numpy.random import randn

In [48]:
x=10
if x>1:
  result="greater than 1"
print(x)
print(result)

10
greater than 1


In [46]:
result=None #intialization
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

-0.8884370061761568
None


If-Else

In [49]:
result=None
x=randn()
if x>1:
  result="greater than 1"
else:
  result="less than 1"
print(x)
print(result)

0.032409907862972744
less than 1


Nested If/ chained if statment


In [55]:
result=None
x=randn()
if x>1:
  result="greater than 1"
elif x<=-1:
  result="less than -1"
else:
  result="between -1 and 1"
print(x)
print(result)

1.7377241152667016
greater than 1


In [56]:
result=None
x=int(input())#runtime input
if x>1:
  result="greater than 1"
elif x<=-1:
  result="less than -1"
else:
  result="between -1 and 1"
print(x)
print(result)

13
13
greater than 1


list

In [57]:
#creating a list
list1=[1,2,3,6,7,'abf',True,20.45]

In [59]:
type(list1)

list

In [60]:
list1[0]

1

In [61]:
list1[6]

True

In [62]:
list1[-1]

20.45

In [63]:
list1[5]="sahana"

In [64]:
print(list1)

[1, 2, 3, 6, 7, 'sahana', True, 20.45]


In [65]:
list1[1:5]

[2, 3, 6, 7]

In [66]:
list1[::2]

[1, 3, 7, True]

In [67]:
list1[::-1]

[20.45, True, 'sahana', 7, 6, 3, 2, 1]

In [69]:
tuple1=(10,'abc','python')

In [70]:
range(230,330)

range(230, 330)

In [71]:
range

range

In [73]:
list(range(230,320))

[230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319]

In [75]:
list2=['sahana','mukunda',1123,30.9,False]

In [76]:
print(list2)

['sahana', 'mukunda', 1123, 30.9, False]


In [78]:
len(list2)

5

In [79]:
type(range)

type

In [80]:
string1="sahanamukunda"

In [81]:
type(string1)

str

In [82]:
max(string1)

'u'

In [83]:
min(string1)

'a'

Array

In [84]:
import numpy as np
a=np.array(list1)
print(a)

['1' '2' '3' '6' '7' 'sahana' 'True' '20.45']


In [85]:
a

array(['1', '2', '3', '6', '7', 'sahana', 'True', '20.45'], dtype='<U32')

dtype means datatype and u is unicode and 32 is value

In [86]:
b=np.array([1234,5678,91011,-2345])

In [88]:
b.mean()

23894.5

In [89]:
b

array([ 1234,  5678, 91011, -2345])

In [90]:
b[::2]

array([ 1234, 91011])

In [91]:
b[1::2]

array([ 5678, -2345])

In [92]:
c=b[2:4]

In [97]:
c

array([91011, -2345])

In [98]:
c[:]

array([91011, -2345])

In [99]:
c[:]=222

In [100]:
c

array([222, 222])

In [101]:
b

array([1234, 5678,  222,  222])